// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYpCahwbpLW_s4KXx2ubJQ5YZOM9Lde2w',
    appId: '1:852359858131:web:28d57293d9e8330c329126',
    messagingSenderId: '852359858131',
    projectId: 'assignment-6a83a',
    authDomain: 'assignment-6a83a.firebaseapp.com',
    storageBucket: 'assignment-6a83a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSb8xqzqaPV_szoHUISfiKSCERG61xUZo',
    appId: '1:852359858131:android:6e4493cde18d830b329126',
    messagingSenderId: '852359858131',
    projectId: 'assignment-6a83a',
    storageBucket: 'assignment-6a83a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNw06S7XH01CPI_snRHl1LCNhXephhn50',
    appId: '1:852359858131:ios:7f481531c98f5173329126',
    messagingSenderId: '852359858131',
    projectId: 'assignment-6a83a',
    storageBucket: 'assignment-6a83a.firebasestorage.app',
    iosBundleId: 'com.example.oruPhonesAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNw06S7XH01CPI_snRHl1LCNhXephhn50',
    appId: '1:852359858131:ios:7f481531c98f5173329126',
    messagingSenderId: '852359858131',
    projectId: 'assignment-6a83a',
    storageBucket: 'assignment-6a83a.firebasestorage.app',
    iosBundleId: 'com.example.oruPhonesAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYpCahwbpLW_s4KXx2ubJQ5YZOM9Lde2w',
    appId: '1:852359858131:web:58f73a5796bd5fa9329126',
    messagingSenderId: '852359858131',
    projectId: 'assignment-6a83a',
    authDomain: 'assignment-6a83a.firebaseapp.com',
    storageBucket: 'assignment-6a83a.firebasestorage.app',
  );
}
